baseURL = "http://codethatapp.github.io/"
languageCode = "en-us"
title = "codethatapp"
theme = "ezhil"
paginate = 8

copyright = "Â© mlblogg"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "ezhil-demo"

summaryLength = 20

[params]
	subtitle = "Hi - i'm Jon, sharing my journey of learning MERN Stack"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "dark" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Tagz"
url = "/tags"
weight = 5

[[menu.main]]
name = "Tagszz"
url = "/tags"
weight = 6


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mlblogg"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mlblogg"


# [[params.social]]
# name = "RSS"
# icon = "rss"
# url = "/index.xml"

[taxonomies]
   tag = "tags"
